#!/usr/bin/env bash
set -euo pipefail

# Usage:
#   DATABASE_URL='postgresql://user@host:5432/jobtrack' ./scripts/list_db_objects.sh [out-file]
# Default out-file: database/db_objects_report.txt

OUT=${1:-database/db_objects_report.txt}
DB=${DATABASE_URL:-}
if [ -z "$DB" ]; then
  echo "ERROR: Set DATABASE_URL (e.g. export DATABASE_URL='postgresql://user@host:5432/jobtrack')" >&2
  exit 2
fi

mkdir -p "$(dirname "$OUT")"
: > "$OUT"

echo "Database objects report generated by scripts/list_db_objects.sh" >> "$OUT"
echo "Database: $DB" >> "$OUT"
echo "Generated: $(date -u +'%Y-%m-%dT%H:%M:%SZ') UTC" >> "$OUT"
echo "" >> "$OUT"

run() {
  echo "-- $1" >> "$OUT"
  # run query and append; show headers
  psql "$DB" -c "$2" >> "$OUT"
  echo "" >> "$OUT"
}

# Tables (public schema)
run "Tables (public)" "\pset format aligned\nSELECT table_name, table_schema FROM information_schema.tables WHERE table_schema='public' AND table_type='BASE TABLE' ORDER BY table_name;"

# Views
run "Views (public)" "\pset format aligned\nSELECT table_name FROM information_schema.views WHERE table_schema='public' ORDER BY table_name;"

# Sequences
run "Sequences (public)" "\pset format aligned\nSELECT sequence_name FROM information_schema.sequences WHERE sequence_schema='public' ORDER BY sequence_name;"

# Indexes
run "Indexes (public)" "\pset format aligned\nSELECT schemaname, tablename, indexname FROM pg_indexes WHERE schemaname='public' ORDER BY tablename, indexname;"

# Triggers
run "Triggers" "\pset format aligned\nSELECT event_object_table, trigger_name, action_timing, event_manipulation FROM information_schema.triggers WHERE trigger_schema='public' ORDER BY event_object_table;"

# Functions (public)
run "Functions (public)" "\pset format aligned\nSELECT n.nspname as schema, p.proname as function, pg_get_function_arguments(p.oid) as args FROM pg_proc p JOIN pg_namespace n ON p.pronamespace=n.oid WHERE n.nspname='public' ORDER BY p.proname;"

# Constraints
run "Constraints (public)" "\pset format aligned\nSELECT constraint_type, table_name, constraint_name FROM information_schema.table_constraints WHERE table_schema='public' ORDER BY table_name;"

# Row counts (for largest tables) - may take time
run "Table sizes (top 20 by total_size)" "\pset format aligned\nSELECT relname AS table, pg_size_pretty(pg_total_relation_size(relid)) AS total_size FROM (SELECT c.oid AS relid, c.relname FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname='public' AND c.relkind='r') t ORDER BY pg_total_relation_size(relid) DESC LIMIT 20;"

echo "Wrote report to $OUT"
chmod 644 "$OUT"
